name: Publish Docker Image
on:
  push:
    branches:
      - 'develop'
    tags:
      - 'v*'
jobs:
  push_to_registry:
    name: Push Image to GitHub Packages
    runs-on: ubuntu-latest
    # Always run against a tag, even if the commit into the tag has [docker skip]
    # within the commit message.
    if: "!contains(github.ref, 'develop') || (!contains(github.event.head_commit.message, 'skip docker') && !contains(github.event.head_commit.message, 'docker skip'))"
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: ghcr.io/pterodactyl/panel
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Bump Version
        if: "!contains(github.ref, 'develop')"
        env:
          REF: ${{ github.ref }}
        run: |
          sed -i "s/    'version' => 'canary',/    'version' => '${REF:11}',/" config/app.php
      - name: Release Production Build
        uses: docker/build-push-action@v2
        if: "!contains(github.ref, 'develop')"
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Release Development Build
        uses: docker/build-push-action@v2
        if: "contains(github.ref, 'develop')"
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
